import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test('one-click workflow, evidence, invalid number, CSV, filters and accessibility', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect(page.getByText('Start with a sample. Follow the evidence.')).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(page.getByText('Skip to demo')).toBeFocused()
  expect(await page.getByText('Skip to demo').evaluate(el => getComputedStyle(el).outlineStyle)).toBe('solid')
  const checkAxe = async () => expect((await new AxeBuilder({ page }).analyze()).violations.filter(v => ['serious', 'critical'].includes(v.impact || ''))).toEqual([])
  await checkAxe()
  await page.screenshot({ path: 'test-results/desktop-landing.png', fullPage: true })
  await page.getByRole('button', { name: 'Load sample list' }).click()
  await expect(page.getByTestId('container-row')).toHaveCount(25)
  expect(await page.getByTestId('container-row').filter({ has: page.getByTestId('exception-badge') }).count()).toBeGreaterThanOrEqual(3)
  await page.screenshot({ path: 'test-results/desktop-watchlist.png', fullPage: true })
  await checkAxe()
  await page.getByRole('button', { name: /Inspect / }).first().click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: 'Event timeline' })).toBeVisible()
  await expect(dialog.getByRole('heading', { name: 'Evidence', exact: true }).first()).toBeVisible()
  await expect(dialog.getByText('Rule:', { exact: true }).first()).toBeVisible()
  await expect(dialog.getByText(/Simulated feed/)).toBeVisible()
  await checkAxe()
  await page.screenshot({ path: 'test-results/desktop-detail.png' })
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await page.getByLabel('Severity', { exact: true }).selectOption('clear')
  await page.getByLabel('Exception family').selectOption('dwell')
  await expect(page.getByText(/No containers match/)).toBeVisible()
  await page.getByLabel('Paste container numbers').fill('CSQU3054384')
  await page.getByRole('button', { name: 'Build watchlist' }).click()
  await expect(page.getByTestId('container-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'Inspect CSQU3054384' }).click()
  await expect(dialog.getByText('Check digit mismatch: expected 3.')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByLabel('Or upload a CSV').setInputFiles({ name: 'numbers.csv', mimeType: 'text/csv', buffer: Buffer.from('container_number\nCSQU3054383\nCSQU3054384') })
  await expect(page.getByTestId('container-row')).toHaveCount(2)
})
test('mobile layout, all sections, errors and unknown route retain feed notice', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/')
  const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await noOverflow()
  await page.screenshot({ path: 'test-results/mobile-landing.png', fullPage: true })
  for (const section of ['#demo', '#method', '#benchmark']) { await page.goto('/' + section); await expect(page.locator('.feed')).toBeVisible(); await noOverflow() }
  await page.getByRole('button', { name: 'Load sample list' }).click()
  await expect(page.getByTestId('container-row')).toHaveCount(25)
  await noOverflow()
  await page.screenshot({ path: 'test-results/mobile-watchlist.png', fullPage: true })
  await page.getByRole('button', { name: /Inspect / }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await noOverflow()
  await page.screenshot({ path: 'test-results/mobile-detail.png' })
  await page.keyboard.press('Escape')
  await page.route('**/api/watchlists/sample', route => route.abort())
  await page.getByRole('button', { name: 'Load sample list' }).click()
  await expect(page.getByRole('alert')).toContainText('wake up')
  await noOverflow()
  await page.goto('/unknown-route')
  await expect(page.locator('.feed')).toBeVisible()
})
