import { useEffect, useRef, useState } from 'react'
import { label, notice, parseNumbers, request, type Row, type Watchlist } from './api'

const source = 'https://github.com/anthonydenis01/middle-watch-agent'
export default function App() {
  const [list, setList] = useState<Watchlist | null>(null)
  const [input, setInput] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [detail, setDetail] = useState<Row | null>(null)
  const [severity, setSeverity] = useState('all')
  const [family, setFamily] = useState('all')
  const [status, setStatus] = useState('all')
  const dialog = useRef<HTMLDialogElement>(null)
  const results = useRef<HTMLElement>(null)
  useEffect(() => { if (detail) dialog.current?.showModal() }, [detail])
  async function run(path: string, body?: BodyInit, headers?: HeadersInit) {
    setBusy(true); setError('')
    try {
      const data = await request<Watchlist>(path, { method: 'POST', body, headers })
      setList(data); setSeverity('all'); setFamily('all'); setStatus('all')
      setTimeout(() => results.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50)
    } catch (e) { setError((e as Error).message) } finally { setBusy(false) }
  }
  async function open(row: Row) {
    setError('')
    try { setDetail(await request<Row>(`/api/containers/${row.id}`)) }
    catch (e) { setError((e as Error).message) }
  }
  const rows = list?.containers.filter(row => (severity === 'all' || row.band === severity) && (family === 'all' || row.exceptions.some(e => e.family === family)) && (status === 'all' || row.status === status)) || []
  return <>
    <a className="skip" href="#demo">Skip to demo</a>
    <div className="feed"><span className="dot" />{notice}</div>
    <header className="topbar wrap"><a className="brand" href="#"><span className="brand-mark" aria-hidden="true">≋</span> MIDDLE WATCH</a><nav aria-label="Main"><a href="#method">How it works</a><a href="#benchmark">The benchmark</a><a href={source}>Source ↗</a></nav></header>
    <main>
      <section className="hero wrap">
        <div><p className="eyebrow">OCEAN FREIGHT · EXCEPTION MONITORING</p><h1>Tracking tells you where.<br /><em>Middle Watch tells you<br className="desktop-break" /> what matters.</em></h1><p className="intro">Turn container journeys into a ranked queue of exceptions. Every flag has a rule, a reason, and the evidence to back it up.</p><div className="hero-actions"><button className="primary" onClick={() => void run('/api/watchlists/sample')} disabled={busy}>{busy ? 'Building your watchlist…' : 'Load sample list'}<span aria-hidden="true">↗</span></button><span>25 simulated containers<br />No signup. No keys.</span></div><p className="byline">Built & evaluated by Anthony Denis <span>·</span> Open source</p></div>
        <aside className="proof" aria-label="Benchmark evidence"><div className="proof-heading"><span className="eyebrow">BENCHMARK RESULTS</span><span aria-hidden="true">↗</span></div><p className="caveat">controlled synthetic benchmark</p><div className="headline-metric">0<span>false positives</span></div><div className="proof-grid"><div><strong>2,393 / 2,393</strong><span>labelled exceptions caught</span></div><div><strong>40,000</strong><span>synthetic rows evaluated</span></div></div><p className="proof-note">Measured against known labels and benign near-misses. Self-authored data; this is not evidence of real-world accuracy.</p><a href="#benchmark">Inspect the method <span aria-hidden="true">→</span></a></aside>
      </section>
      <section id="demo" className="workspace wrap" aria-label="Interactive demo"><div className="section-heading"><div><p className="eyebrow">01 / TRY THE WORKFLOW</p><h2>Your watch, in one place.</h2></div><span className="pill">SIMULATED WORKSPACE</span></div>
        <div className="input-grid"><form onSubmit={e => { e.preventDefault(); const numbers = parseNumbers(input); if (!numbers.length || numbers.length > 100) { setError('Enter between 1 and 100 container numbers.'); return }; void run('/api/watchlists', JSON.stringify({ numbers }), { 'Content-Type': 'application/json' }) }}><label htmlFor="numbers">Paste container numbers</label><textarea id="numbers" value={input} onChange={e => setInput(e.target.value)} placeholder="CSQU3054383" rows={2} aria-describedby="input-help" /><div className="form-bottom"><small id="input-help">Up to 100 · separated by spaces, commas or new lines</small><button disabled={busy} className="secondary" type="submit">Build watchlist →</button></div></form><div className="upload"><label htmlFor="csv">Or upload a CSV</label><p>One column: <code>container_number</code><br />Up to 100 rows · 200 KB max</p><input id="csv" type="file" accept=".csv,text/csv" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (file) { if (file.size > 200000) { setError('CSV must be at most 200 KB.'); return }; const body = new FormData(); body.append('file', file); void run('/api/watchlists/csv', body) }; e.target.value = '' }} /></div></div>
        {busy && <p role="status" className="message">Generating simulated journeys and checking the rules. A sleeping API may need a moment.</p>}
        {error && <div role="alert" className="error"><strong>Unable to complete this run.</strong> {error} <button onClick={() => setError('')}>Dismiss</button></div>}
        <section ref={results} className="results" aria-label="Watchlist results" aria-live="polite">
          {list ? <><div className="results-heading"><h3>{list.summary.total} containers <span>· {list.summary.flagged} flagged · {list.summary.invalid} invalid</span></h3><small>Ranked by severity · expires after 24 hours</small></div><div className="filters"><label>Severity<select aria-label="Severity" value={severity} onChange={e => setSeverity(e.target.value)}><option value="all">All severities</option>{['critical', 'high', 'medium', 'clear'].map(s => <option key={s}>{s}</option>)}</select></label><label>Exception family<select aria-label="Exception family" value={family} onChange={e => setFamily(e.target.value)}><option value="all">All families</option>{['routing_change', 'vessel_swap', 'dwell', 'eta_drift', 'transit_time'].map(f => <option key={f} value={f}>{label(f)}</option>)}</select></label><label>Status<select aria-label="Status" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option>{[...new Set(list.containers.map(r => r.status))].map(s => <option key={s} value={s}>{label(s)}</option>)}</select></label><button className="text-button" onClick={() => { setSeverity('all'); setFamily('all'); setStatus('all') }}>Reset filters</button></div>{rows.length ? <div className="table-scroll"><table><caption className="sr-only">Container watchlist, sorted by severity</caption><thead><tr><th>Container / status</th><th>Next milestone</th><th>ETA</th><th>Exceptions</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{rows.map(row => <tr key={row.id} data-testid="container-row"><td><button className="number" onClick={() => void open(row)}>{row.number}</button><span className="row-status">{label(row.status)}</span></td><td>{row.next_milestone || 'Check number'}</td><td>{row.eta?.slice(0, 10) || '—'}</td><td><div className="badges">{!row.valid ? <span className="badge invalid">Invalid number</span> : row.exceptions.length ? row.exceptions.map((f, i) => <span className={`badge ${row.band}`} data-testid="exception-badge" key={i}>{label(f.family)}</span>) : <span className="clear-label">No exception</span>}</div></td><td><button className="row-open" aria-label={`Inspect ${row.number}`} onClick={() => void open(row)}>↗</button></td></tr>)}</tbody></table></div> : <div className="empty">No containers match these filters. Reset filters to see your watchlist.</div>}</> : <div className="empty"><span className="empty-symbol" aria-hidden="true">≋</span><div><h3>Start with a sample. Follow the evidence.</h3><p>Load the sample list above, or add numbers to see which journeys need attention.</p></div><span className="empty-arrow" aria-hidden="true">↗</span></div>}
        </section>
      </section>
      <section id="method" className="wrap method"><p className="eyebrow">02 / UNDER THE HOOD</p><h2>Deterministic by design.<br />Explainable at every step.</h2><div className="steps">{[['01', 'Validate', 'ISO 6346 check digits catch invalid inputs before a journey is generated.'], ['02', 'Simulate & detect', 'A seeded provider generates journeys. Five existing detectors compare the booking, events and current state.'], ['03', 'Review the evidence', 'Inspect ranked exceptions, the timeline and field-level differences. Template explanations work without any model key.']].map(([n, title, text]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="architecture">React + TypeScript <span>→</span> FastAPI <span>→</span> SimulatedProvider + rule engine <span>→</span> SQL database</p></section>
      <section id="benchmark" className="benchmark wrap"><div><p className="eyebrow">03 / SHOW YOUR WORK</p><h2>Good recall is only<br />half the question.</h2><p>A detector that flags everything catches every exception. The useful test is what it leaves alone.</p><a href={`${source}/blob/app/docs/benchmark/README.md`}>Read the benchmark & limitations ↗</a></div><div><p className="caveat">controlled synthetic benchmark</p><p><strong>40,000 rows. 2,393 / 2,393 caught. 0 false positives.</strong></p><p>Seed 7 · snapshot 2026-08-03. False positives count reported incidents on unlabelled containers, divided by all reported incidents. Additional findings on labelled containers are not false positives.</p><p>Benign cases include ETA jitter, voyage renumbering, equivalent hubs and dwell below the reporting rules. Repeated identifiers and overlapping categories are disclosed in the source.</p><p className="limitation">The generator and detectors share an author. These results demonstrate reproducibility and rule behavior, not accuracy on unseen operational data.</p></div></section>
    </main><footer className="wrap"><span className="brand">MIDDLE WATCH</span><p>Built, evaluated, open source. Anthony Denis.</p><a href={source}>Explore the code ↗</a></footer>
    <dialog ref={dialog} onClose={() => setDetail(null)} aria-labelledby="detail-title"><div className="drawer-feed">{notice}</div>{detail && <div className="drawer-body"><div className="drawer-heading"><div><p className="eyebrow">CONTAINER DETAIL</p><h2 id="detail-title">{detail.number}</h2></div><button className="secondary" autoFocus onClick={() => dialog.current?.close()}>Close</button></div>{!detail.valid ? <div className="error"><h3>Invalid number</h3><p>{detail.invalid_reason}</p></div> : <><p>{detail.origin} → {detail.destination} <span className="pill">{label(detail.status)}</span></p><h3>Why this needs attention</h3><p>{detail.explanation?.text}</p>{detail.explanation?.action && <p><strong>Next action:</strong> {detail.explanation.action}</p>}{detail.explanation?.draft_message && <><h3>Draft update</h3><p>{detail.explanation.draft_message}</p></>}<h3>Exceptions & evidence</h3>{detail.exceptions.length ? detail.exceptions.map((f, i) => <article className="finding" key={i}><span className={`badge ${detail.band}`}>{label(f.family)} · severity {f.severity}</span><h4>{f.title}</h4><p className="rule"><strong>Rule:</strong> <code>{f.rule_id}</code></p><h5>Evidence</h5>{f.evidence?.map((item, j) => <dl key={j}>{Object.entries(item).map(([key, value]) => <div key={key}><dt>{label(key)}</dt><dd>{typeof value === 'object' ? JSON.stringify(value) : String(value ?? '—')}</dd></div>)}</dl>)}</article>) : <p>No exception crossed the reporting threshold.</p>}<h3>Event timeline</h3><ol className="timeline">{detail.events?.map((event, i) => <li key={i}><time>{event.ts.replace('T', ' ').slice(0, 16)}</time><strong>{label(event.code)}</strong><span>{event.location_unlocode} · {event.vessel} · {event.voyage}</span></li>)}</ol><p className="detail-note">Generated snapshot, not a current tracking update. {detail.explanation?.source === 'model' ? 'AI draft: verify against the rule evidence before use.' : 'Explanations use deterministic templates.'}</p></>}</div>}</dialog>
  </>
}
